name: Regenerate

on: [workflow_dispatch]

jobs:
  regenerate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Regenerate list of errors and warnings
      run: dotnet run -- -l -c -r main -o CSharpErrorsAndWarnings.md
    - name: Commit changes
      run: |
        git config user.name "Github Actions"
        git config user.email "githubactions@thomaslevesque.net"
        git add .
        git commit -m "Regenerate list of errors and warnings" || echo "No changes to commit"
        git push
